"""Institutional PDF market report export (spec §50)."""

import io
from datetime import datetime, timezone

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.services.market_narrative import generate_narrative

STYLES = getSampleStyleSheet()
TITLE_STYLE = ParagraphStyle("RSETitle", parent=STYLES["Title"], textColor=colors.HexColor("#1F4E78"))
HEADING_STYLE = ParagraphStyle("RSEHeading", parent=STYLES["Heading2"], textColor=colors.HexColor("#1F4E78"),
                                spaceBefore=14, spaceAfter=6)
META_STYLE = ParagraphStyle("RSEMeta", parent=STYLES["Normal"], textColor=colors.HexColor("#666666"), fontSize=9)
BODY_STYLE = STYLES["BodyText"]

TABLE_HEADER_BG = colors.HexColor("#1F4E78")


def _table(headers, rows, col_widths=None):
    data = [headers] + rows
    t = Table(data, colWidths=col_widths, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), TABLE_HEADER_BG),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D9D9D9")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F5F8FA")]),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ALIGN", (1, 1), (-1, -1), "RIGHT"),
    ]))
    return t


def _fmt(v, empty="—"):
    return empty if v is None else str(v)


def export_report_to_pdf(report) -> io.BytesIO:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=1.5 * cm, bottomMargin=1.5 * cm,
                             leftMargin=1.5 * cm, rightMargin=1.5 * cm)
    story = []

    story.append(Paragraph("Rwanda Stock Exchange — Market Report", TITLE_STYLE))
    report_date = report.report_date.isoformat() if report.report_date else "Unknown"
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    story.append(Paragraph(
        f"Report Date: {report_date} &nbsp;|&nbsp; Source: {report.source or 'Official RSE Market Report'} "
        f"&nbsp;|&nbsp; Generated: {generated} &nbsp;|&nbsp; Status: {report.approval_status.title()}",
        META_STYLE,
    ))
    story.append(Spacer(1, 10))

    story.append(Paragraph("Market Summary", HEADING_STYLE))
    story.append(Paragraph(generate_narrative(report), BODY_STYLE))

    stats = report.market_statistics
    if stats:
        story.append(Paragraph("Key Statistics", HEADING_STYLE))
        rows = [
            ["Shares Traded", _fmt(f"{stats.shares_traded:,}" if stats.shares_traded is not None else None)],
            ["Equity Turnover (Frw)", _fmt(f"{stats.equity_turnover:,.0f}" if stats.equity_turnover is not None else None)],
            ["Bond Turnover (Frw)", _fmt(f"{stats.bond_turnover:,.0f}" if stats.bond_turnover is not None else None)],
            ["Number of Deals", _fmt(stats.number_of_deals)],
            ["Market Capitalization (Frw)", _fmt(f"{stats.market_capitalization:,.0f}" if stats.market_capitalization is not None else None)],
        ]
        story.append(_table(["Metric", "Value"], rows, col_widths=[9 * cm, 8 * cm]))

    equities = list(report.equities)
    if equities:
        story.append(Paragraph("Equities", HEADING_STYLE))
        rows = [
            [e.symbol, _fmt(e.closing_price), _fmt(e.previous_close), _fmt(e.change), _fmt(e.volume)]
            for e in equities
        ]
        story.append(_table(["Security", "Close", "Prev Close", "Change", "Volume"], rows))

    indices = list(report.indices)
    if indices:
        story.append(Paragraph("Indices", HEADING_STYLE))
        rows = [[i.index_name, _fmt(i.current_value), _fmt(i.previous_value), _fmt(i.percentage_change)]
                for i in indices]
        story.append(_table(["Index", "Current", "Previous", "% Change"], rows))

    bonds = list(report.bonds)
    if bonds:
        story.append(Paragraph("Bonds", HEADING_STYLE))
        rows = [[b.security, _fmt(b.maturity_date), _fmt(b.coupon), _fmt(b.close_price)] for b in bonds]
        story.append(_table(["Security", "Maturity", "Coupon", "Close/Yield"], rows))

    fx = list(report.exchange_rates)
    if fx:
        story.append(Paragraph("Exchange Rates", HEADING_STYLE))
        rows = [[f.currency, _fmt(f.buy_rate), _fmt(f.sell_rate), _fmt(f.average_rate)] for f in fx]
        story.append(_table(["Currency", "Buy", "Sell", "Average"], rows))

    story.append(Spacer(1, 16))
    story.append(Paragraph(
        "This report was generated by the RSE Intelligence platform from an official RSE market report. "
        "Calculated and narrative figures are derived exclusively from validated source data.",
        META_STYLE,
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer
